server:
  port: 8888
spring:
  application:
    name: magnet-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cccchenccc/magnet-profiles
          default-label: master
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    log-delta-diff: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file: log/${spring.application.name}.log
          
#/{name}/{profile}[/{label}]
#/{name}-{profile}.yml
#/{label}/{name}-{profile}.yml