server:
  port: 8888
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: magnet-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cccchenccc/magnet-profiles
          default-label: master
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file: log/${spring.application.name}.log
management:
  security:
    enabled: false
          
#/{name}/{profile}[/{label}]
#/{name}-{profile}.yml
#/{label}/{name}-{profile}.yml