server:
  port: 8888
spring:
  application:
    name: magnet-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cccchenccc/magnet-profiles
          default-label: master
          force-pull: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    log-delta-diff: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file: log/${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
    profiles: ${spring.profiles.active}
          
#/{name}/{profile}[/{label}]
#/{name}-{profile}.yml
#/{label}/{name}-{profile}.yml