security:
  user:
    password: qqq
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      scope:
        read, write
    authorization:
      check-token-access: isAuthenticated()
spring:
  application:
    name: magnet-auth
  data:
    mongodb:
      database: auth
      host: localhost
      port: 27017
      repositories:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
    view:
      prefix: /pages/
      suffix: .html
server:
  port: 8090