server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${spring.application.name}
spring:
  application:
    name: magnet-gateway
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
  sleuth:
    sampler:
      probability: 0.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
            - '*'
            allowedHeaders:
            - '*'
            allowCredentials: true
            maxAge: 1800
      default-filters: null
      routes:
      - id: athena_route
        uri: lb://MAGNET-ATHENA
        predicates:
        - Path=/athena/**
        filters:
        - StripPrefix=1
      - id: lucia_route
        uri: lb://MAGNET-LUCIA
        predicates:
        - Path=/lucia/**
        filters:
        - StripPrefix=1
      - id: atropos_route
        uri: lb://MAGNET-ATROPOS
        predicates:
        - Path=/atropos/**
        filters:
        - StripPrefix=1
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      grant-type: implicit
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
logging:
  file: log/${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
    port: ${server.port}