server:
  port: 8761
spring:
  application:
    name: magnet-eureka
  data:
    mongodb:
      database: magnet-eureka
      host: 10.0.0.4
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    registry-fetch-interval-seconds: 30
    log-delta-diff: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  file: log/${spring.application.name}.log
#  level:
#    org:
#      springframework: 
#        web: DEBUG
        
#management:
#  security:
#    enabled: false
