server:
  port: 8110
  servlet:
    session:
      cookie:
        name: ${spring.application.name}
spring:
  main:
    banner-mode: LOG
  application:
    name: magnet-athena
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
  sleuth:
    sampler:
      probability: 0.0
  security:
    oauth2:
      client:
        registration:
          my-client-1:
            client-name: Magnet Client
            client-id: magnet-client
            client-secret: passw0rd
            provider: my-oauth-provider
            client-authentication-method: basic
            authorization-grant-type: password
        provider:
          my-oauth-provider: 
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
            user-info-uri: http://localhost:8090/oauth/check_token
            jwk-set-uri: http://localhost:8090/oauth/token_key
      resourceserver:
#        token-info-uri: http://localhost:8090/oauth/check_token
#        preferTokenInfo: true
        jwt:
          jwk-set-uri: http://localhost:8090/oauth/token_key
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    log-delta-diff: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
  okhttp:
    enabled: true
  httpclient:
    enabled: false
ribbon:
  ReadTimeout: 3000
  SocketTimeout: 3000
  okhttp:
    enabled: true
  httpclient:
    enabled: false
logging:
  file: log/${spring.application.name}.log
  max-size: 1MB
  max-history: 100
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: FULL
info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
  git: ${git}
  build: ${build}