server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${spring.application.name}
spring:
  application:
    name: magnet-zuul
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
  sleuth:
    sampler:
      probability: 0.0
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  ribbonIsolationStrategy: SEMAPHORE
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
    time-unit: MILLISECONDS
  threadPool:
    useSeparateThreadPools: true
    threadPoolKeyPrefix: zuulgw
  routes:
    athena:
      path: /athena/**
      sensitiveHeaders:
      serviceId: MAGNET-ATHENA
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: MAGNET-AUTH

ribbon:
  ReadTimeout: 3000
  SocketTimeout: 3000
#If you want to configure the socket timeouts and read timeouts for requests proxied through Zuul, you have two options, based on your configuration:
#If Zuul uses service discovery, you need to configure these timeouts with the ribbon.ReadTimeout and ribbon.SocketTimeout Ribbon properties.
#If you have configured Zuul routes by specifying URLs, you need to use zuul.host.connect-timeout-millis and zuul.host.socket-timeout-millis.
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      grant-type: implicit
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
logging:
  file: log/${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
    port: ${server.port}