spring:
  profiles: dev
  application:
    name: magnet-lucia
---
server:
  port: 8100
  context-path: /magnet-lucia
  session:
    cookie:
      name: LUCIASESSIONID
spring:
  profiles: local
  application:
    name: magnet-lucia
  data:
    mongodb:
      database: magnet-lucia
      host: localhost
      port: 27017
      repositories:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    status-page-url-path: ${server.context-path}/info
    health-check-url-path: ${server.context-path}/health
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    log-delta-diff: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      grant-type: implicit
      access-token-uri: http://localhost:8090/magnet-auth/oauth/token
      user-authorization-uri: http://localhost:8090/magnet-auth/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/magnet-auth/oauth/check_token
      preferTokenInfo: true
feign:
  hystrix:
    enabled: true
magnet-athena:
  ribbon:
    OkToRetryOnAllOperations: false
    MaxAutoRetries: 0
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000
  eager-load:
    enabled: true
    clients: magnet-athena
hystrix: 
  shareSecurityContext: true
  command: 
    "AthenaClient#oneUserByNamePath(String)": 
      execution: 
        isolation: 
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
    default: 
      execution: 
        isolation: 
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
#management:
#  security:
#    enabled: false
endpoints:
    sensitive: true
info:
  app:
    name: ${spring.application.name}
    context-path: ${server.context-path}
    profiles: ${spring.profiles}
logging:
  file: log/${spring.application.name}.log
#  level:
#    org:
#      springframework:
#        security: DEBUG