spring:
  profiles: dev
  application:
    name: magnet-lucia
---
server:
  port: 8100
spring:
  profiles: local
  application:
    name: magnet-lucia
  data:
    mongodb:
      database: lucia
      host: localhost
      port: 27017
      repositories:
        enabled: true
logging:
  file: log/${spring.application.name}.log
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      clientAuthenticationScheme: form
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
    sso:
      login-path: /welcome
feign:
  hystrix:
    enabled: true
magnet-athena:
  ribbon:
    OkToRetryOnAllOperations: false
    MaxAutoRetries: 0
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000
hystrix: 
  shareSecurityContext: true
  command: 
    "AthenaClient#oneUserByNamePath(String)": 
      execution: 
        isolation: 
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
    default: 
      execution: 
        isolation: 
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
management:
  security:
    enabled: false