spring:
  profiles: dev
  application:
    name: magnet-lucia
---
server:
  port: 8100
spring:
  profiles: local
  application:
    name: magnet-lucia
  data:
    mongodb:
      database: lucia
      host: localhost
      port: 27017
      repositories:
        enabled: true
logging:
  file: log/${spring.application.name}.log
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
management:
  security:
    enabled: false