spring:
  profiles: dev
  application:
    name: magnet-lucia
---
server:
  port: 8100
spring:
  profiles: local
  application:
    name: magnet-lucia
  data:
    mongodb:
      database: lucia
      host: localhost
      port: 27017
      repositories:
        enabled: true
logging:
  file: log/${spring.application.name}.log
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
#      authentication-scheme: 
      clientAuthenticationScheme: form
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
#    sso:
#      login-path: http://www.baidu.com
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
#          strategy: THREAD
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
management:
  security:
    enabled: false