server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${spring.application.name}
spring:
  application:
    name: magnet-gateway
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
  sleuth:
    sampler:
      probability: 0.0
  cloud:
    gateway:
      routes:
      - id: custom_route
        uri: lb://MAGNET-ATHENA
        predicates:
        - Path=/athena/**
        filters:
        - name: RewritePath
          args: 
            regexp: /athena/(?<remaining>.*)
            replacement: /${remaining}
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file: log/${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
    port: ${server.port}