server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
    session:
      cookie:
        name: ${spring.application.name}
spring:
  application:
    name: magnet-gateway
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
  cloud:
    gateway:
      routes:
      - id: custom_route
        uri: http://magnet-athena
        predicates:
        - Path=/athena/
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    client:
      client-id: magnet-client
      client-secret: passw0rd
      grant-type: implicit
      access-token-uri: http://localhost:8090/magnet-auth/oauth/token
      user-authorization-uri: http://localhost:8090/magnet-auth/oauth/authorize
    resource:
      token-info-uri: http://localhost:8090/magnet-auth/oauth/check_token
      preferTokenInfo: true
logging:
  file: log/${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: ${spring.application.name}
    context-path: ${server.servlet.context-path}
    profiles: ${spring.profiles}
